In [1]:
import pandas as pd

In [24]:
trainingset = pd.read_csv("./dataset/semeval_test.tsv", delimiter='\t', index_col=0)
trainingset

                                                    text               label
id
8001   The most common <e1>audits</e1> were about <e2...       Message-Topic
8002   The <e1>company</e1> fabricates plastic <e2>ch...    Product-Producer
8003   The school <e1>master</e1> teaches the lesson ...   Instrument-Agency
8004   The suspect dumped the dead <e1>body</e1> into...  Entity-Destination
8005   Avian <e1>influenza</e1> is an infectious dise...        Cause-Effect
...                                                  ...                 ...
10713  After seating all the idols, which itself take...   Instrument-Agency
10714  The minister attributed the slow production of...    Product-Producer
10715  The <e1>umbrella</e1> <e2>frame</e2> is provid...     Component-Whole
10716  Manos: The Hands of Fate is a low-budget horro...    Product-Producer
10717  A few days before the service, Tom Burris had ...  Entity-Destination

[2717 rows x 2 columns]

In [26]:
with open("./dataset/semeval_label.tsv") as f:
    label = [l.strip() for l in f.readlines()]

label

['Other',
 'Component-Whole',
 'Cause-Effect',
 'Entity-Destination',
 'Member-Collection',
 'Message-Topic',
 'Entity-Origin',
 'Product-Producer',
 'Content-Container',
 'Instrument-Agency']

In [27]:
for l in label:
    trainingset.replace(to_replace=l, value=label.index(l), inplace=True)

In [28]:
trainingset

                                                    text  label
id
8001   The most common <e1>audits</e1> were about <e2...      5
8002   The <e1>company</e1> fabricates plastic <e2>ch...      7
8003   The school <e1>master</e1> teaches the lesson ...      9
8004   The suspect dumped the dead <e1>body</e1> into...      3
8005   Avian <e1>influenza</e1> is an infectious dise...      2
...                                                  ...    ...
10713  After seating all the idols, which itself take...      9
10714  The minister attributed the slow production of...      7
10715  The <e1>umbrella</e1> <e2>frame</e2> is provid...      1
10716  Manos: The Hands of Fate is a low-budget horro...      7
10717  A few days before the service, Tom Burris had ...      3

[2717 rows x 2 columns]

In [22]:
trainingset.to_csv("test.tsv", sep="\t")